In [174]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import scale
from numpy import linalg as LA

In [175]:
# mat = np.array([[90,60,90],[90,90,30],[60,60,60],[60,60,90],[30,30,30]])
mat = np.array([[90,90,60,60,30],[60,90,60,60,30],[90,30,60,90,30]])
mat.shape

(3, 5)

In [176]:
cv_mat = np.cov(mat, bias=True) # for population covaraince 

## Step 1: Covarince 

In [177]:
cv_mat

array([[ 504.,  360.,  180.],
       [ 360.,  360.,    0.],
       [ 180.,    0.,  720.]])

## Step 2: Eigen values and eigen vecotors

In [178]:
ew, ev = LA.eig(cv_mat) # eigen values and , eigen vectors 

In [179]:
ew # eigen values

array([  44.81966028,  910.06995304,  629.11038668])

In [180]:
ev # eigen vectors

array([[ 0.6487899 , -0.65580225, -0.3859988 ],
       [-0.74104991, -0.4291978 , -0.51636642],
       [-0.17296443, -0.62105769,  0.7644414 ]])

## Step 3 : Check for eigen values are correct or not 

In [181]:
# check for c1 and c2 for eigen values verification 
# ax = Yx


In [182]:
c1 = np.dot(cv_mat, ev[:, 1])
c1

array([-596.82592739, -390.60001855, -565.2059424 ])

In [183]:
c2 = np.dot(ew[1], ev[:, 1])

In [184]:
c2

array([-596.82592739, -390.60001855, -565.2059424 ])

## Step 4: Choose best eigen vectros from corresponding eigen values 



In [185]:

final_ev = ev[:, 0:2]
final_ev

array([[ 0.6487899 , -0.65580225],
       [-0.74104991, -0.4291978 ],
       [-0.17296443, -0.62105769]])

In [186]:
final_ev.shape

(3, 2)

## Step 4: Multiply with best eigen vector on real data # (2 * 3) * (3 * 5)

In [187]:
final_op = np.dot(final_ev.T, mat)
final_op

array([[  -1.63870252,  -13.4923342 ,  -15.91346662,  -21.10239948,
          -7.95673331],
       [-140.6692628 , -116.28173533, -102.36346447, -120.99519515,
         -51.18173223]])

In [188]:
# cov_mat = np.stack((x, y), axis = 0)  

In [189]:
final_op.T

array([[  -1.63870252, -140.6692628 ],
       [ -13.4923342 , -116.28173533],
       [ -15.91346662, -102.36346447],
       [ -21.10239948, -120.99519515],
       [  -7.95673331,  -51.18173223]])

In [190]:
## Above matric is the lower dimensional data

In [191]:
#ref: https://towardsdatascience.com/the-mathematics-behind-principal-component-analysis-fff2d7f4b643