In [1]:
import numpy as np
from scipy import sparse

X = np.random.uniform(size=(6, 6))
print(X)

[[0.60944232 0.25657472 0.20751898 0.81055401 0.17199358 0.4552633 ]
 [0.70219666 0.75043437 0.03495985 0.29747239 0.87136761 0.35725552]
 [0.90997506 0.65767809 0.35717664 0.37022771 0.8026996  0.21649834]
 [0.4504551  0.57672403 0.88855537 0.77771025 0.84134411 0.44130106]
 [0.08114774 0.00230679 0.7775508  0.06936019 0.1584812  0.11077189]
 [0.34882594 0.22713131 0.88140417 0.45767552 0.31243631 0.46835158]]


In [2]:
import numpy as np
from scipy import sparse

X = np.random.uniform(size=(6, 6))
print(X)

[[0.14593363 0.21377337 0.9463818  0.55588445 0.07908407 0.02927248]
 [0.97499961 0.9269379  0.53127198 0.54916467 0.25841083 0.28598533]
 [0.43938597 0.84143226 0.46743852 0.41642746 0.31300035 0.62457579]
 [0.14473136 0.64312647 0.28836139 0.78441501 0.38109699 0.6774959 ]
 [0.29852428 0.55390097 0.0509726  0.51311264 0.36814353 0.06901426]
 [0.17685432 0.94615773 0.96845256 0.43326958 0.38649126 0.18099814]]


In [3]:
import numpy as np
from scipy import sparse

X = np.random.uniform(size=(6, 6))
print(X)

[[0.7706324  0.04015141 0.38356912 0.40554354 0.45772294 0.48250381]
 [0.59015089 0.50427092 0.72742118 0.29904751 0.45614421 0.25205944]
 [0.89616207 0.81934925 0.60582638 0.29381351 0.38057658 0.42059448]
 [0.00727264 0.51856091 0.58648208 0.99416192 0.53839153 0.2535684 ]
 [0.43302567 0.15839679 0.7701811  0.1731939  0.74654223 0.40196965]
 [0.93847863 0.94081751 0.06478045 0.73034925 0.32627083 0.32496728]]


In [6]:
X_csr = sparse.csr_matrix(X)
print(X_csr)

  (0, 0)	0.7706324012395458
  (0, 1)	0.04015140981178145
  (0, 2)	0.3835691225708493
  (0, 3)	0.4055435416362887
  (0, 4)	0.4577229398244991
  (0, 5)	0.48250381271858933
  (1, 0)	0.5901508878164338
  (1, 1)	0.5042709213889801
  (1, 2)	0.7274211766268731
  (1, 3)	0.29904751120905027
  (1, 4)	0.45614421300159136
  (1, 5)	0.25205944267991964
  (2, 0)	0.8961620699799573
  (2, 1)	0.8193492494663133
  (2, 2)	0.6058263772422777
  (2, 3)	0.2938135115829601
  (2, 4)	0.3805765788913642
  (2, 5)	0.4205944789884145
  (3, 0)	0.007272644002473738
  (3, 1)	0.5185609131841417
  (3, 2)	0.5864820834076039
  (3, 3)	0.9941619212831747
  (3, 4)	0.5383915311425537
  (3, 5)	0.2535684012265279
  (4, 0)	0.4330256663509665
  (4, 1)	0.15839678796796564
  (4, 2)	0.7701810964217691
  (4, 3)	0.1731938993888119
  (4, 4)	0.7465422327408316
  (4, 5)	0.4019696512153814
  (5, 0)	0.9384786326527349
  (5, 1)	0.9408175093663822
  (5, 2)	0.06478044563366403
  (5, 3)	0.7303492534627388
  (5, 4)	0.32627082765548754
  (5, 5)	0

In [7]:
X_csc = sparse.csc_matrix(X)
print(X_csc)

  (0, 0)	0.7706324012395458
  (1, 0)	0.5901508878164338
  (2, 0)	0.8961620699799573
  (3, 0)	0.007272644002473738
  (4, 0)	0.4330256663509665
  (5, 0)	0.9384786326527349
  (0, 1)	0.04015140981178145
  (1, 1)	0.5042709213889801
  (2, 1)	0.8193492494663133
  (3, 1)	0.5185609131841417
  (4, 1)	0.15839678796796564
  (5, 1)	0.9408175093663822
  (0, 2)	0.3835691225708493
  (1, 2)	0.7274211766268731
  (2, 2)	0.6058263772422777
  (3, 2)	0.5864820834076039
  (4, 2)	0.7701810964217691
  (5, 2)	0.06478044563366403
  (0, 3)	0.4055435416362887
  (1, 3)	0.29904751120905027
  (2, 3)	0.2938135115829601
  (3, 3)	0.9941619212831747
  (4, 3)	0.1731938993888119
  (5, 3)	0.7303492534627388
  (0, 4)	0.4577229398244991
  (1, 4)	0.45614421300159136
  (2, 4)	0.3805765788913642
  (3, 4)	0.5383915311425537
  (4, 4)	0.7465422327408316
  (5, 4)	0.32627082765548754
  (0, 5)	0.48250381271858933
  (1, 5)	0.25205944267991964
  (2, 5)	0.4205944789884145
  (3, 5)	0.2535684012265279
  (4, 5)	0.4019696512153814
  (5, 5)	0

In [8]:
print(X_csr.toarray())


[[0.7706324  0.04015141 0.38356912 0.40554354 0.45772294 0.48250381]
 [0.59015089 0.50427092 0.72742118 0.29904751 0.45614421 0.25205944]
 [0.89616207 0.81934925 0.60582638 0.29381351 0.38057658 0.42059448]
 [0.00727264 0.51856091 0.58648208 0.99416192 0.53839153 0.2535684 ]
 [0.43302567 0.15839679 0.7701811  0.1731939  0.74654223 0.40196965]
 [0.93847863 0.94081751 0.06478045 0.73034925 0.32627083 0.32496728]]


In [9]:
import numpy as np
from scipy import sparse

X = np.random.uniform(size=(10000, 10000))
X[X < 0.7] = 0
X_csr = sparse.csr_matrix(X)

print(f"Size in bytes of original matrix: {X.nbytes}")
print(f"Size in bytes of compressed sparse row matrix: {X_csr.data.nbytes + X_csr.indptr.nbytes + X_csr.indices.nbytes}")

Size in bytes of original matrix: 800000000
Size in bytes of compressed sparse row matrix: 359996240


In [10]:
# ref: https://www.kdnuggets.com/2020/05/sparse-matrix-representation-python.html